pipeline:
  build:
    image: microsoft/dotnet:2.1-sdk
    commands:
      - cd PSD2Payment
      - dotnet restore
      - dotnet publish -c Release -o out
  test:
    image: microsoft/dotnet:2.1-sdk
    commands:
      - cd PSD2Payment.Test
      - dotnet restore
      - dotnet test
  push:
    image: plugins/docker
    context: PSD2Payment
    dockerfile: PSD2Payment/Dockerfile
    repo: asseco/sinergija-demo
    secrets: [docker_username, docker_password]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy_env:
    image: asseco/sinergija-deploy
    git_repo: strainovic/pis
    helm_chart: pis

  run_api_test:
    image: asseco/api-test
    commands:
      - cd api-tests
      - newman run postman_collection.json -e postman_environment.json --global-var "env=http://sinergija-test.asseco.rs" --reporters cli,html --reporter-html-export report.html

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: drone
    username: drone
    when:
      status: [ failure, success ]
    template: >
      {{#success build.status}}
        Repo {{repo.name}} build {{build.number}} succeeded. Good job {{build.author}}.
      {{else}}
        Repo {{repo.name}} build {{build.number}} failed. {{build.author}} Fix me!.
      {{/success}}
   
   
     