pipeline:
  build:
    image: microsoft/dotnet:2.1-sdk
    commands:
      - dotnet restore
      - dotnet publish -c Release -o out
  push:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: asseco/sinergija-demo
    secrets: [docker_username, docker_password]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock