// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSD2Payment.Database;

namespace PSD2Payment.Migrations
{
    [DbContext(typeof(PISDBContext))]
    [Migration("20181021124553_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("psd2")
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PSD2Payment.Database.Model.Account", b =>
                {
                    b.Property<string>("Iban")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bban");

                    b.Property<string>("Bic");

                    b.Property<string>("CashAccountType");

                    b.Property<string>("Currency");

                    b.Property<string>("Details");

                    b.Property<string>("LinkedAccounts");

                    b.Property<string>("Links")
                        .HasColumnName("Links");

                    b.Property<string>("Msisdn");

                    b.Property<string>("Name");

                    b.Property<string>("Product");

                    b.Property<string>("ResourceId");

                    b.Property<string>("Status");

                    b.Property<string>("Usage");

                    b.Property<string>("_Balances")
                        .HasColumnName("Balances");

                    b.HasKey("Iban");

                    b.ToTable("Accounts");

                    b.HasData(
                        new { Iban = "RS35105008123123123173", CashAccountType = "multi-currency", Currency = "RSD", Links = "{\"balances\":null,\"transactions\":null}", Name = "Multi-currency Current account", Product = "current-account", ResourceId = "159c9e96-2247-4bdf-864a-8704f708861a", Status = "active", _Balances = "[{\"balanceAmount\":{\"currency\":\"EUR\",\"amount\":10000.0},\"balanceType\":\"current\",\"lastChangeDateTime\":\"2018-10-21T14:45:53.5153003+02:00\",\"referenceDate\":null,\"lastCommittedTransaction\":null},{\"balanceAmount\":{\"currency\":\"RSD\",\"amount\":128000.0},\"balanceType\":\"current\",\"lastChangeDateTime\":\"2018-10-21T14:45:53.5209942+02:00\",\"referenceDate\":null,\"lastCommittedTransaction\":null}]" },
                        new { Iban = "RS3510523423123123123173", CashAccountType = "multi-currency", Currency = "EUR", Links = "{\"balances\":null,\"transactions\":null}", Name = "Multi-currency Current account", Product = "current-account", ResourceId = "c6122c5d-a990-4234-86a4-6894775c1c79", Status = "active", _Balances = "[{\"balanceAmount\":{\"currency\":\"EUR\",\"amount\":6500.0},\"balanceType\":\"current\",\"lastChangeDateTime\":\"2018-10-21T14:45:53.5213122+02:00\",\"referenceDate\":null,\"lastCommittedTransaction\":null},{\"balanceAmount\":{\"currency\":\"RSD\",\"amount\":765000.0},\"balanceType\":\"current\",\"lastChangeDateTime\":\"2018-10-21T14:45:53.5213137+02:00\",\"referenceDate\":null,\"lastCommittedTransaction\":null}]" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
